apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-otel-demo
  labels:
    app: gin-otel-demo
spec:
  selector:
    matchLabels:
      app: gin-otel-demo
  template:
    metadata:
      name: gin-otel-demo
      labels:
        app: gin-otel-demo
    spec:
      shareProcessNamespace: true
      volumes:
        - name: time
          hostPath:
            path: /etc/localtime
      containers:
        - name: gin-otel-demo
          image: gin-otel-demo:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: MYSQL_USERNAME
            value: "root"
          - name: MYSQL_PASSWORD
            value: "MK5i^6@S1d"
          - name: MYSQL_HOST
            value: "10.82.69.76:3306"
          - name: MYSQL_DB_NAME
            value: "gin-otel-demo"
          - name: REDIS_MODEL
            value: "standalone"
          - name: REDIS_HOST
            value: "10.82.69.69:6379"
          - name: REDIS_PASSWORD
            value: "d8m413WGF9CV"
          - name: OTEL_SERVICE_NAME
            value: "gin-otel-demo"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "tempo.monitoring:4317"
          - name: OTEL_K8S_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: OTEL_RESOURCE_ATTRIBUTES_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: OTEL_RESOURCE_ATTRIBUTES_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: 'k8s.namespace.name=$(OTEL_K8S_NAMESPACE),k8s.node.name=$(OTEL_RESOURCE_ATTRIBUTES_NODE_NAME),k8s.pod.name=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME)'
          ports:
          - containerPort: 9090 # 容器端口
          volumeMounts:
          - name: time
            readOnly: true
            mountPath: /etc/localtime
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: gin-otel-demo
spec:
  type: NodePort
  ports:
    - port: 9090 # 服务端口
  selector:
    app: gin-otel-demo
